name: Build

on:
  workflow_call:
# push:
#   branches:
#     - dev
# pull_request:
#   branches:
#     - dev
#     - main

env:
  NEXT_PUBLIC_BASE_URL: "https://portal.usstm.ca"

jobs:
  build:
    name: Build static website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: speelbarrow/checkout-and-setup@v1.3
      - name: Build using Next.JS
        run:  npx next build
      - name: Upload static website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .next/
